#!/usr/bin/env bash

if [ -z "$1" ]; then
  echo "Add a Bucket Name"
  exit 1
fi

if [ -z "$2" ]; then
  echo "Add a Bucket Name"
  exit 1
fi

Bucket_Name=$1
Directory=$2
File_Name=$(basename "$Directory") 

aws s3api put-object \
 --bucket "$Bucket_Name" \
 --body "$Directory" \
 --key "$File_Name"
