#!/usr/bin/env bash

# create a VPC
VPC_ID=$(aws ec2 create-vpc \
--cidr-block 10.0.0.0/16 \
--query Vpc.VpcId \
--output text)

echo "VPC_ID: $VPC_ID"

# create a Subnet
SUBNET_ID=$(aws ec2 create-subnet \
--vpc-id $VPC_ID \
--cidr-block 10.0.0.0/24 \
--query Subnet.SubnetId \
--output text)

echo "SUBNET_ID: $SUBNET_ID"

# create an internet-gateway
IGW=$(aws ec2 create-internet-gateway \
--query InternetGateway.InternetGatewayId \
--output text)

echo "IGW: $IGW"

# attach internet-gateway to VPC
aws ec2 attach-internet-gateway \
--internet-gateway-id $IGW \
--vpc-id $VPC_ID
echo "IGW ATTACHED"

# get router-table ID
RT_ID=$(aws ec2 describe-route-tables \
--filters "Name=vpc-id,Values=$VPC_ID" "Name=association.main,Values=true" \
--query "RouteTables[*].RouteTableId" \
--output text)

# explicitly associate subnet
ASSOC_ID=$(aws ec2 associate-route-table \
--route-table-id $RT_ID \
--subnet-id $SUBNET_ID \
--query AssociationId \
--output text)
echo "RT ASSOCIATED TO SUBNET"

# add a route for our RT to our IGW
aws ec2 create-route \
--route-table-id $RT_ID \
--destination-cidr-block 0.0.0.0/0 \
--gateway-id $IGW
echo "RT ASSOCIATED TO IGW"

echo "./delete-vpc $VPC_ID $IGW $SUBNET_ID $RT_ID $ASSOC_ID"