#!/usr/bin/env bash

if [ -z "$1" ]; then
  echo "Add a VPC ID"
else
  export VPC_ID="$1"
fi

if [ -z "$2" ]; then
  echo "Add a VPC ID"
else
  export IGW="$2"
fi

if [ -z "$3" ]; then
  echo "Add a VPC ID"
else
  export SUBNET_ID="$3"
fi

if [ -z "$4" ]; then
  echo "Add a VPC ID"
else
  export RT_ID="$4"
fi

if [ -z "$5" ]; then
  echo "Add a VPC ID"
else
  export ASSOC_ID="$5"
fi

# detach IGW and VPC
aws ec2 detach-internet-gateway --internet-gateway-id $IGW --vpc-id $VPC_ID

# disassociate-route-table
aws ec2 disassociate-route-table \
--association-id $ASSOC_ID


# delete subnet
aws ec2 delete-subnet --subnet-id $SUBNET_ID

#delete internet-gateway
aws ec2 delete-internet-gateway --internet-gateway-id $IGW

# delete route table
# aws ec2 delete-route-table --route-table-id $RT_ID

# delete vpc
aws ec2 delete-vpc --vpc-id $VPC_ID

echo "ALL DELETED"